name: Scala CI

on:
  push:
    branches:
      - main
      - MVP
  pull_request:
    branches:
      - main
      - MVP

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: sbt coverage test
      - name: Coverage Report
        run: sbt coverageReport
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: "test-results/**/*.xml"
          check_run_annotations: all tests, skipped tests
          check_run_annotations_branch: "*"
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Formatting
        run: sbt scalafmtSbtCheck scalafmtCheck test:scalafmtCheck